### ISSUE TITLE
Оплата через киви

### ISSUE THREAD

**Issue by FlameProfi** [07artem132/WHMCS-Payment-Gateways-yandex-money-cards#1]
А ты случайно не делал оплату через киви?
Если да, можешь поделиться?

**Comment by 07artem132** [comment]
> А ты случайно не делал оплату через киви?
> Если да, можешь поделиться?

Данный модуль имеется, однако он платный.

**Comment by FlameProfi** [comment]
А сколько он стоит? Просто очень бы хотелось подключить оплату через киви

**Comment by 07artem132** [comment]
500р
