### ISSUE TITLE
Проблема в работе.

### ISSUE THREAD

**Issue by EveryDayRains** [07artem132/WHMCS-Payment-Gateways-yandex-money-cards#2]
Изменил в модуле все с money.yandex.ru на yoomoney.ru. Счёт делает, но вебхук не работает. Не можете подсказать как пофиксить?
```
[WHMCS Application] ERROR: ArgumentCountError: Too few arguments to function logModuleCall(), 3 passed in E:\OpenServer\domains\localhost\modules\gateways\callback\yandex.php on line 12 and at least 4 expected in E:\OpenServer\domains\localhost\includes\functions.php:0 Stack trace: #0 E:\OpenServer\domains\localhost\modules\gateways\callback\yandex.php(12): logModuleCall('yandex', 'Start_Vertifi_T...', Array) #1 {main} {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function logModuleCall(), 3 passed in E:\\OpenServer\\domains\\localhost\\modules\\gateways\\callback\\yandex.php on line 12 and at least 4 expected at E:\\OpenServer\\domains\\localhost\\includes\\functions.php:0)"} []
 ```
(логи с локал openserver, не нашёл на хосте логи нормальные)
 8.1.3 версия панели. пыха 7.

**Comment by EveryDayRains** [comment]
UPD: проблема была только в 12 строчке, теперь вопрос. Обязательно она должна быть? А то я в комент кинул, все норм теперь. Мб она чет делает.. код обфусцированный, я не понял

**Comment by 07artem132** [comment]
Вы о функции logModuleCall ? Ее можно спокойно закомментировать эта функция используется для ведения журнала посредством whmcs на тот случай если будут не воспроизводимые ошибки дабы можно было попросить лог. Пожалуйста сделайте пул реквест дабы другие могли так же пользоваться исправленным модулем.
